"""
Cross-Encoder Reranker Node for Multi-Agent RAG.

Executes Stage 2 high-precision reranking over candidate chunks fetched in Stage 1:
1. Scores query-chunk pairs using cross-attention relevance.
2. Sorts candidates and filters out weak distractors.
3. Implements an explicit abstention threshold (default: 0.25): if all chunks score
   below this threshold, flags the query as out-of-scope to prevent hallucinations.
4. Uses resilient hybrid engine: FlashRank (ONNX) with seamless LLM-as-a-Reranker fallback.
"""

import json
import os
import re
import sys
from typing import Dict, Any, List, Tuple, Optional

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from agents.state import AgentState
from agents.llm import get_llm
from config import (
    ABSTENTION_THRESHOLD,
    RERANK_TOP_K,
    FAST_PATH_TOP_K,
    HIGH_CONFIDENCE_RERANK_THRESHOLD,
    RERANKER_MODEL_NAME
)

RERANKER_SYSTEM_PROMPT = """You are a High-Precision Academic Retrieval Reranker.
Evaluate the semantic relevance of each candidate evidence passage to the user query.
Assign each passage a normalized relevance score between 0.00 and 1.00:
- 0.80 - 1.00: Directly answers or provides essential, conclusive evidence for the query.
- 0.50 - 0.79: Moderately relevant; provides useful context, background, or partial evidence.
- 0.00 - 0.49: Distractor, prior work, tangential mention, or completely irrelevant.

Output strictly valid JSON with the following structure:
{
  "rankings": [
    {"id": 1, "score": 0.95, "reason": "Directly answers the query with empirical evidence."},
    {"id": 2, "score": 0.15, "reason": "Mentions prior related work, not the target answer."}
  ]
}
"""


class CrossEncoderReranker:
    """
    Two-Stage Cross-Encoder Reranker supporting local ONNX (FlashRank)
    with seamless LLM-based Cross-Attention fallback.
    """

    def __init__(self, model_name: str = RERANKER_MODEL_NAME):
        self.model_name = model_name
        self.flashrank_client = None
        self._init_flashrank()

    def _init_flashrank(self):
        """Attempts to load local FlashRank ONNX cross-encoder."""
        try:
            from flashrank import Ranker
            self.flashrank_client = Ranker(model_name=self.model_name)
            print(f"[+] FlashRank Cross-Encoder loaded: {self.model_name}")
        except Exception as e:
            # Fallback to high-precision LLM-as-a-Reranker if offline or weights not cached
            self.flashrank_client = None

    def _collect_queries(self, query: str, sub_queries: Optional[List[str]] = None) -> List[str]:
        """
        Collects the primary user query and any sub-queries dynamically
        generated by the Planner Agent. Zero regexes or hardcoded substitutions.
        """
        queries = [query.strip()]
        if sub_queries:
            for sq in sub_queries:
                sq_clean = sq.strip()
                if sq_clean and sq_clean.lower() != query.strip().lower() and sq_clean not in queries:
                    queries.append(sq_clean)
        return queries

    def rerank(
        self,
        query: str,
        chunks: List[Dict[str, Any]],
        sub_queries: Optional[List[str]] = None,
        top_k: int = RERANK_TOP_K,
        threshold: float = ABSTENTION_THRESHOLD
    ) -> Tuple[List[Dict[str, Any]], float, bool, Dict[str, int]]:
        """
        Reranks a list of candidate passages for a given query and its variants.
        
        Returns:
            - reranked_chunks: Top-k passages above threshold.
            - max_score: Highest relevance score across all candidates.
            - is_relevant: True if max_score >= threshold, False otherwise.
            - token_usage: Dict with prompt, completion, and total tokens used.
        """
        if not chunks:
            return [], 0.0, False, {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

        # 1. Try local FlashRank if initialized
        if self.flashrank_client is not None:
            try:
                from flashrank import RerankRequest
                passages = [
                    {"id": idx, "text": c.get("text", ""), "meta": c.get("metadata", {})}
                    for idx, c in enumerate(chunks)
                ]

                query_variants = self._collect_queries(query, sub_queries)
                best_scores = {idx: 0.0 for idx in range(len(chunks))}

                # Score each candidate chunk across all query variants; retain the maximum score
                for q_var in query_variants:
                    req = RerankRequest(query=q_var, passages=passages)
                    results = self.flashrank_client.rerank(req)
                    for res in results:
                        c_id = res["id"]
                        score = float(res.get("score", 0.0))
                        if score > best_scores[c_id]:
                            best_scores[c_id] = score

                ranked_chunks = []
                for idx, c in enumerate(chunks):
                    orig_chunk = c.copy()
                    orig_chunk["rerank_score"] = round(best_scores[idx], 4)
                    ranked_chunks.append(orig_chunk)

                ranked_chunks.sort(key=lambda c: c.get("rerank_score", 0.0), reverse=True)
                max_score = ranked_chunks[0]["rerank_score"] if ranked_chunks else 0.0
                is_relevant = max_score >= threshold
                golden_chunks = [c for c in ranked_chunks if c.get("rerank_score", 0.0) >= threshold][:top_k]

                return golden_chunks, max_score, is_relevant, {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}
            except Exception as e:
                print(f"  [!] Note: FlashRank runtime fallback to LLM reranker ({e}).")

        # 2. Resilient High-Precision LLM Cross-Attention Reranker (Groq)
        return self._rerank_with_llm(query, chunks, top_k=top_k, threshold=threshold)

    def _rerank_with_llm(
        self,
        query: str,
        chunks: List[Dict[str, Any]],
        top_k: int = RERANK_TOP_K,
        threshold: float = ABSTENTION_THRESHOLD
    ) -> Tuple[List[Dict[str, Any]], float, bool, Dict[str, int]]:
        """LLM-based Cross-Attention Reranking via Groq with exact token accounting."""
        llm = get_llm(temperature=0.0)
        token_usage = {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

        if llm is None:
            # Safe dry-run passthrough if no API key
            for c in chunks:
                c["rerank_score"] = c.get("rrf_score", 0.5)
            return chunks[:top_k], 0.5, True, token_usage

        # Format candidates (limiting snippet length to preserve tokens)
        candidate_blocks = []
        for idx, c in enumerate(chunks, 1):
            text_snippet = c.get("text", "").strip()[:400].replace("\n", " ")
            meta = c.get("metadata", {})
            pid = meta.get("paper_id", "")
            sec = meta.get("section", "")
            candidate_blocks.append(f"[{idx}] (Paper: {pid}, Section: {sec}) {text_snippet}")

        user_content = (
            f"User Query: {query}\n\n"
            f"Candidate Passages:\n" + "\n".join(candidate_blocks) + "\n\n"
            f"Output strictly valid JSON with score (0.00 to 1.00) for all {len(chunks)} candidates."
        )

        try:
            response = llm.invoke([
                {"role": "system", "content": RERANKER_SYSTEM_PROMPT},
                {"role": "user", "content": user_content}
            ])

            usage = getattr(response, "usage_metadata", {}) or {}
            token_usage["prompt_tokens"] = usage.get("input_tokens", 0)
            token_usage["completion_tokens"] = usage.get("output_tokens", 0)
            token_usage["total_tokens"] = usage.get("total_tokens", 0)

            # Parse JSON rankings
            content = response.content.strip()
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()

            data = json.loads(content)
            rankings = data.get("rankings", [])
            score_map = {item.get("id"): float(item.get("score", 0.0)) for item in rankings}

            ranked_chunks = []
            for idx, c in enumerate(chunks, 1):
                chunk_copy = c.copy()
                chunk_copy["rerank_score"] = round(score_map.get(idx, 0.0), 4)
                ranked_chunks.append(chunk_copy)

            ranked_chunks.sort(key=lambda c: c.get("rerank_score", 0.0), reverse=True)
            max_score = ranked_chunks[0]["rerank_score"] if ranked_chunks else 0.0
            is_relevant = max_score >= threshold
            golden_chunks = [c for c in ranked_chunks if c.get("rerank_score", 0.0) >= threshold][:top_k]

            return golden_chunks, max_score, is_relevant, token_usage
        except Exception as e:
            print(f"  [!] Note: LLM reranking parse error ({e}). Falling back to top RRF chunks.")
            for c in chunks:
                c["rerank_score"] = c.get("rrf_score", 0.5)
            return chunks[:top_k], 0.5, True, token_usage


# Shared singleton instance
_RERANKER_INSTANCE = None


def get_reranker() -> CrossEncoderReranker:
    """Returns singleton instance of CrossEncoderReranker."""
    global _RERANKER_INSTANCE
    if _RERANKER_INSTANCE is None:
        _RERANKER_INSTANCE = CrossEncoderReranker()
    return _RERANKER_INSTANCE


def rerank_node(state: AgentState) -> Dict[str, Any]:
    """
    LangGraph node wrapper for Cross-Encoder Reranker.
    Scores and filters Stage 1 candidate passages into the golden top 3-4 chunks.
    """
    query = state.get("query", "")
    route = state.get("route", "pinpoint_retrieval")
    chunks = state.get("retrieved_chunks", [])

    # Whole-document retrieval: validate relevance of query against resolved paper content
    if route == "whole_document":
        print(f"\n[RERANKER] Stage 2: Validating relevance for whole-document query across paper chunks...")
        reranker = get_reranker()
        _, max_score, is_relevant, tokens = reranker.rerank(
            query=query,
            chunks=chunks[:6],  # sample key introductory/methodological chunks
            top_k=RERANK_TOP_K,
            threshold=ABSTENTION_THRESHOLD
        )
        p_tok = state.get("prompt_tokens", 0) + tokens.get("prompt_tokens", 0)
        c_tok = state.get("completion_tokens", 0) + tokens.get("completion_tokens", 0)
        t_tok = state.get("total_tokens", 0) + tokens.get("total_tokens", 0)

        if not is_relevant:
            print(f"  [!] Abstention Triggered: Whole-document query does not match paper content (max score: {max_score:.4f} < {ABSTENTION_THRESHOLD}).")
            return {
                "retrieved_chunks": [],
                "reranked_chunks": [],
                "max_rerank_score": max_score,
                "is_relevant_evidence": False,
                "prompt_tokens": p_tok,
                "completion_tokens": c_tok,
                "total_tokens": t_tok
            }

        print(f"  * Whole-document relevance verified (max score: {max_score:.4f} >= {ABSTENTION_THRESHOLD}). Preserving full reading order.")
        return {
            "retrieved_chunks": chunks,
            "reranked_chunks": chunks,
            "max_rerank_score": max_score,
            "is_relevant_evidence": True,
            "prompt_tokens": p_tok,
            "completion_tokens": c_tok,
            "total_tokens": t_tok
        }

    print(f"\n[RERANKER] Stage 2: Cross-Encoder reranking over {len(chunks)} candidate chunks...")
    reranker = get_reranker()
    golden_chunks, max_score, is_relevant, tokens = reranker.rerank(
        query=query,
        chunks=chunks,
        sub_queries=state.get("sub_queries", []),
        top_k=RERANK_TOP_K,
        threshold=ABSTENTION_THRESHOLD
    )

    # Accumulate token usage if LLM reranker was used
    p_tok = state.get("prompt_tokens", 0) + tokens.get("prompt_tokens", 0)
    c_tok = state.get("completion_tokens", 0) + tokens.get("completion_tokens", 0)
    t_tok = state.get("total_tokens", 0) + tokens.get("total_tokens", 0)

    print(f"  * Top relevance score: {max_score:.4f} | Relevant evidence found: {is_relevant}")
    if is_relevant:
        route = state.get("route", "pinpoint_retrieval")
        # Part B.3: If fast-path simple_direct and confidence is very high (>= 0.85), reduce chunks to top 1-2
        if route == "simple_direct" and max_score >= HIGH_CONFIDENCE_RERANK_THRESHOLD:
            golden_chunks = golden_chunks[:FAST_PATH_TOP_K]
            print(f"  * [FAST PATH] Very high confidence ({max_score:.4f} >= {HIGH_CONFIDENCE_RERANK_THRESHOLD}). Context reduced to {len(golden_chunks)} golden chunks.")

        print(f"  * Filtered {len(chunks)} candidate chunks down to {len(golden_chunks)} golden evidence chunks:")
        for idx, gc in enumerate(golden_chunks, 1):
            sec = gc.get("metadata", {}).get("section", "General")
            pg = gc.get("metadata", {}).get("page_num", "?")
            print(f"    [{idx}] Section: {sec} (Pg {pg}) | Cross-Encoder Score: {gc.get('rerank_score', 0.0):.4f}")
    else:
        print(f"  [!] Abstention Triggered: All candidate chunks scored below relevance threshold ({ABSTENTION_THRESHOLD}).")

    return {
        "retrieved_chunks": golden_chunks,
        "reranked_chunks": golden_chunks,
        "max_rerank_score": max_score,
        "is_relevant_evidence": is_relevant,
        "prompt_tokens": p_tok,
        "completion_tokens": c_tok,
        "total_tokens": t_tok
    }
