"""
Retriever Agent Node for Multi-Agent Financial RAG.

Executes hybrid search (ChromaDB dense + BM25 sparse via Reciprocal Rank Fusion) across
all sub-queries generated by the Planner. Deduplicates overlapping chunks, aggregates RRF
relevance scores, and formats the evidence package for the Reranker and Synthesizer.
Includes entity-aware ticker routing to prevent cross-company chunk contamination.
"""

import sys
import os
import re
from typing import Dict, Any, List, Set

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from agents.state import AgentState
from ingestion.indexer import HybridIndexer
from config import TOP_K_PER_SUBQUERY, MAX_TOTAL_CHUNKS

_INDEXER_INSTANCE = None
_ENTITY_REGISTRY_CACHE = None


def get_indexer() -> HybridIndexer:
    """Returns a cached singleton instance of HybridIndexer."""
    global _INDEXER_INSTANCE
    if _INDEXER_INSTANCE is None:
        _INDEXER_INSTANCE = HybridIndexer()
        _INDEXER_INSTANCE.load_indexes()
    return _INDEXER_INSTANCE


from agents.registry import extract_target_tickers, get_alias_to_ticker_map

def get_entity_registry() -> Dict[str, str]:
    """Dynamically returns the name-to-ticker mapping from agents.registry."""
    return get_alias_to_ticker_map()



def retrieve_evidence(
    state: AgentState,
    top_k_per_subquery: int = TOP_K_PER_SUBQUERY,
    max_total_chunks: int = MAX_TOTAL_CHUNKS
) -> Dict[str, Any]:
    """
    Retriever Node function for Lean Enterprise Financial RAG (Option A):
    1. Deterministically dispatches query to target company tickers (0ms).
    2. For multi-company comparisons, executes balanced parallel hybrid search per entity.
    3. For single-company queries, scopes hybrid search to that ticker.
    4. Merges and deduplicates hits with Reciprocal Rank Fusion (RRF).
    """
    query = state.get("query", "")
    existing_chunks = state.get("retrieved_chunks", [])
    indexer = get_indexer()

    # Deterministic Entity Dispatch
    global_tickers = extract_target_tickers(query)

    print(f"\n[RETRIEVER] Option A Lean Dispatch:")
    if global_tickers:
        print(f"  * Entity Focus: {sorted(list(global_tickers))}")
    else:
        print(f"  * Entity Focus: Global (All registered 10-K filings)")

    chunk_map = {}

    # Preserve prior iteration chunks if compatible
    for c in existing_chunks:
        cid = c["chunk_id"]
        c_ticker = c.get("metadata", {}).get("ticker", "")
        if not global_tickers or c_ticker in global_tickers:
            chunk_map[cid] = c

    # Execute Balanced Parallel Hybrid Retrieval
    if len(global_tickers) >= 2:
        # Cross-company comparison: fetch equal quota per entity
        quota = max(4, 12 // len(global_tickers))
        for tkr in sorted(list(global_tickers)):
            hits = indexer.hybrid_search(query=query, top_k=quota, ticker_filter=tkr)
            print(f"  * Dedicated retrieval for [{tkr}]: {len(hits)} chunks")
            for hit in hits:
                cid = hit["chunk_id"]
                if cid in chunk_map:
                    chunk_map[cid]["rrf_score"] = chunk_map[cid].get("rrf_score", 0.0) + hit.get("rrf_score", 0.0)
                else:
                    chunk_map[cid] = hit
    elif len(global_tickers) == 1:
        # Single-company query: focused hybrid search
        tkr = next(iter(global_tickers))
        hits = indexer.hybrid_search(query=query, top_k=10, ticker_filter=tkr)
        print(f"  * Focused retrieval for [{tkr}]: {len(hits)} chunks")
        for hit in hits:
            cid = hit["chunk_id"]
            if cid in chunk_map:
                chunk_map[cid]["rrf_score"] = chunk_map[cid].get("rrf_score", 0.0) + hit.get("rrf_score", 0.0)
            else:
                chunk_map[cid] = hit
    else:
        # Global query: across all companies
        hits = indexer.hybrid_search(query=query, top_k=10, ticker_filter=None)
        print(f"  * Global retrieval: {len(hits)} chunks")
        for hit in hits:
            cid = hit["chunk_id"]
            if cid in chunk_map:
                chunk_map[cid]["rrf_score"] = chunk_map[cid].get("rrf_score", 0.0) + hit.get("rrf_score", 0.0)
            else:
                chunk_map[cid] = hit

    # Sort merged chunks: if multiple entities are targeted, guarantee equal quota
    if len(global_tickers) >= 2:
        quota_per_entity = max(2, max_total_chunks // len(global_tickers))
        balanced_chunks = []
        for tkr in sorted(list(global_tickers)):
            tkr_chunks = sorted(
                [c for c in chunk_map.values() if c.get("metadata", {}).get("ticker") == tkr],
                key=lambda c: c.get("rrf_score", 0.0),
                reverse=True
            )[:quota_per_entity]
            balanced_chunks.extend(tkr_chunks)
        
        used_ids = {c["chunk_id"] for c in balanced_chunks}
        remaining_slots = max_total_chunks - len(balanced_chunks)
        if remaining_slots > 0:
            remaining = sorted(
                [c for c in chunk_map.values() if c["chunk_id"] not in used_ids],
                key=lambda c: c.get("rrf_score", 0.0),
                reverse=True
            )[:remaining_slots]
            sorted_chunks = balanced_chunks + remaining
        else:
            sorted_chunks = balanced_chunks
    else:
        sorted_chunks = sorted(
            chunk_map.values(),
            key=lambda c: c.get("rrf_score", 0.0),
            reverse=True
        )[:max_total_chunks]

    print(f"  * Aggregated and deduplicated into {len(sorted_chunks)} top evidence chunks.")
    for i, c in enumerate(sorted_chunks, 1):
        meta = c.get("metadata", {})
        sec = meta.get("section", "General")
        ticker = meta.get("ticker", meta.get("paper_id", "UNKNOWN"))
        print(f"    [{i}] [{ticker}] {sec} | Score: {c.get('rrf_score', 0.0):.4f}")

    return {
        "retrieved_chunks": sorted_chunks,
        "total_retrieved_count": len(sorted_chunks)
    }
