"""
Retriever Agent Node for Multi-Agent RAG.

Executes hybrid search (ChromaDB dense + BM25 sparse via Reciprocal Rank Fusion) across
all sub-queries generated by the Planner. Deduplicates overlapping chunks, aggregates RRF
relevance scores, and formats the evidence package for the Synthesizer.
"""

import sys
import os
from typing import Dict, Any, List

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from agents.state import AgentState
from ingestion.indexer import HybridIndexer
from config import TOP_K_PER_SUBQUERY, MAX_TOTAL_CHUNKS

# Shared indexer instance to avoid reloading disk indexes on every step
_INDEXER_INSTANCE = None


def get_indexer() -> HybridIndexer:
    """Returns a cached singleton instance of HybridIndexer."""
    global _INDEXER_INSTANCE
    if _INDEXER_INSTANCE is None:
        _INDEXER_INSTANCE = HybridIndexer()
        _INDEXER_INSTANCE.load_indexes()
    return _INDEXER_INSTANCE


def select_stratified_chunks(chunks: List[Dict[str, Any]], target_budget: int = 20) -> List[Dict[str, Any]]:
    """
    Section-aware stratified selection of chunks for whole-document synthesis.
    Guarantees representation across Abstract, Introduction, Method, Experiments,
    Results, Ablation Studies, and Conclusions up to target_budget (default: 20).
    """
    if len(chunks) <= target_budget:
        return chunks

    # 1. Group chunks by section while preserving original indices
    sections: Dict[str, List[tuple[int, Dict[str, Any]]]] = {}
    for idx, c in enumerate(chunks):
        sec = c.get("metadata", {}).get("section", "Unknown")
        sections.setdefault(sec, []).append((idx, c))

    # Identify low-priority boilerplate sections that shouldn't crowd out scientific results
    boilerplate_keys = {"acknowledgments", "acknowledgement", "ethical considerations"}
    
    scientific_chunks = []
    boilerplate_chunks = []
    for sec, items in sections.items():
        if sec.lower() in boilerplate_keys:
            boilerplate_chunks.extend(items)
        else:
            scientific_chunks.extend(items)

    scientific_chunks.sort(key=lambda x: x[0])

    if len(scientific_chunks) <= target_budget:
        selected = [c for _, c in scientific_chunks]
        remaining = target_budget - len(selected)
        for _, c in boilerplate_chunks[:remaining]:
            selected.append(c)
        selected.sort(key=lambda c: (c.get("metadata", {}).get("page_num", 0), c.get("chunk_id", "")))
        return selected

    # Sample proportionally across sections
    selected_indices = set()
    
    # Priority anchors:
    # 1. First chunk (Abstract / Title)
    selected_indices.add(0)
    
    # 2. Key section heads (first chunk of each scientific section)
    for sec, items in sections.items():
        if sec.lower() not in boilerplate_keys and items:
            selected_indices.add(items[0][0])
            # If section is Conclusion, Results, or Ablation, also anchor its closing chunk
            sec_lower = sec.lower()
            if any(k in sec_lower for k in ["conclusion", "result", "ablation", "discussion"]):
                selected_indices.add(items[-1][0])

    # 3. Evenly distribute remaining budget across scientific chunks
    remaining_budget = target_budget - len(selected_indices)
    if remaining_budget > 0:
        unselected_scientific = [idx for idx, _ in scientific_chunks if idx not in selected_indices]
        if unselected_scientific:
            step = len(unselected_scientific) / remaining_budget
            for k in range(remaining_budget):
                idx_to_add = unselected_scientific[int(k * step)]
                selected_indices.add(idx_to_add)

    # 4. If anchors exceeded target_budget, trim from the largest section (e.g. Method)
    if len(selected_indices) > target_budget:
        sec_counts = {}
        for idx in selected_indices:
            sec = chunks[idx].get("metadata", {}).get("section", "Unknown")
            sec_counts[sec] = sec_counts.get(sec, 0) + 1
        
        excess = len(selected_indices) - target_budget
        candidates_to_trim = []
        for sec, count in sorted(sec_counts.items(), key=lambda x: x[1], reverse=True):
            if count > 2:
                items = [idx for idx in selected_indices if chunks[idx].get("metadata", {}).get("section") == sec]
                candidates_to_trim.extend(items[1:-1])
        
        for idx in candidates_to_trim[:excess]:
            selected_indices.remove(idx)

    selected_list = [chunks[i] for i in sorted(list(selected_indices))]
    return selected_list


def retrieve_evidence(
    state: AgentState,
    top_k_per_subquery: int = TOP_K_PER_SUBQUERY,
    max_total_chunks: int = MAX_TOTAL_CHUNKS
) -> Dict[str, Any]:
    """
    Retriever Node function for LangGraph:
    - If whole-document route: pulls section-aware stratified chunks (up to 20) for the resolved paper.
    - If pinpoint route: runs hybrid search for each planned sub-query and merges hits with RRF.
    """
    route = state.get("route", "pinpoint_retrieval")
    paper_id = state.get("resolved_paper_id")
    sub_queries = state.get("sub_queries", [state.get("query", "")])
    existing_chunks = state.get("retrieved_chunks", [])

    indexer = get_indexer()

    # 1. Whole-Document Path: Section-Aware Stratified Retrieval (Budget: 20 Chunks)
    if route == "whole_document" and paper_id:
        print(f"\n[RETRIEVER] Fetching full paper sequence for ID: {paper_id}...")
        all_chunks = indexer.get_all_chunks_for_paper(paper_id)
        
        target_budget = 10
        selected_chunks = select_stratified_chunks(all_chunks, target_budget=target_budget)
        
        retrieved_sections = list(dict.fromkeys(c.get("metadata", {}).get("section", "Unknown") for c in selected_chunks))
        retrieved_pages = sorted(list(set(c.get("metadata", {}).get("page_num", 0) for c in selected_chunks)))
        
        print(f"  * Retrieved {len(selected_chunks)}/{len(all_chunks)} chunks via Section-Aware Stratified Selection.")
        print(f"  * Covered Pages: {retrieved_pages}")
        print(f"  * Covered Sections: {', '.join(retrieved_sections)}")

        return {
            "retrieved_chunks": selected_chunks,
            "total_retrieved_count": len(selected_chunks)
        }

    # 2. Pinpoint Path: Multi-subquery Hybrid Search & Fusion
    print(f"\n[RETRIEVER] Executing hybrid retrieval across {len(sub_queries)} sub-queries...")

    chunk_map = {}  # chunk_id -> dict with combined score
    
    # Also preserve any previously retrieved chunks from prior iterations
    for c in existing_chunks:
        cid = c["chunk_id"]
        chunk_map[cid] = c

    for idx, sub_q in enumerate(sub_queries, 1):
        results = indexer.hybrid_search(sub_q, top_k=top_k_per_subquery)
        print(f"  * Sub-query [{idx}]: '{sub_q[:60]}...' -> Found {len(results)} hits.")

        for hit in results:
            cid = hit["chunk_id"]
            if cid in chunk_map:
                # Accumulate relevance score if returned by multiple sub-queries
                chunk_map[cid]["rrf_score"] = chunk_map[cid].get("rrf_score", 0.0) + hit.get("rrf_score", 0.0)
            else:
                chunk_map[cid] = hit

    # Sort merged chunks by accumulated RRF score
    sorted_chunks = sorted(
        chunk_map.values(),
        key=lambda c: c.get("rrf_score", 0.0),
        reverse=True
    )[:max_total_chunks]

    print(f"  * Aggregated and deduplicated into {len(sorted_chunks)} top evidence chunks.")
    for i, c in enumerate(sorted_chunks, 1):
        meta = c.get("metadata", {})
        sec = meta.get("section", "Unknown")
        pg = meta.get("page_num", "?")
        pid = meta.get("paper_id", "")
        print(f"    [{i}] Paper: {pid} | Section: {sec} (Pg {pg}) | Score: {c.get('rrf_score', 0.0):.4f}")

    return {
        "retrieved_chunks": sorted_chunks,
        "total_retrieved_count": len(sorted_chunks)
    }
